{
 "title": "k6 - Minimal",
 "panels": [
  {
   "title": "HTTP Req Duration (p95)",
   "type": "graph",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "measurement": "http_req_duration",
     "groupBy": [
      { "type": "time", "params": [ "10s" ] }
     ],
     "select": [
      [
       { "type": "field", "params": [ "value" ] },
       {
        "type": "percentile",
        "params": [
         95
        ]
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "HTTP RPS",
   "type": "graph",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "measurement": "http_reqs",
     "groupBy": [
      { "type": "time", "params": [ "10s" ] }
     ],
     "select": [
      [
       { "type": "field", "params": [ "count" ] },
       {
        "type": "mean",
        "params": []
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Fail Rate",
   "type": "graph",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "measurement": "http_req_failed",
     "groupBy": [
      { "type": "time", "params": [ "10s" ] }
     ],
     "select": [
      [
       { "type": "field", "params": [ "rate" ] },
       {
        "type": "mean",
        "params": []
       }
      ]
     ]
    }
   ]
  }
 ]
}